trigger:
  - master
  - main

pr:
  branches:
    include:
      - master
      - main
      - "*"

pool:
  vmImage: ubuntu-latest

variables:
  - group: api-keys
  - name: Agent.Source.Git.ShallowFetchDepth
    value: 0
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: '1'

steps:
  - checkout: self
    submodules: true
    fetchDepth: 0

  - task: UseDotNet@2
    displayName: 'Install .NET 10 SDK'
    inputs:
      packageType: sdk
      version: '10.x'

  - pwsh: dotnet tool install -g DotnetDeployer.Tool
    displayName: Install DotnetDeployer

  - pwsh: |
      dotnetdeployer --dry-run
    displayName: Create release packages only (dry run)
    condition: and(succeeded(), not(or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))))
    env:
      GITHUB_TOKEN: $(GitHubApiKey)
      ANDROID_KEYSTORE_BASE64: $(AndroidBase64Keystore)
      ANDROID_SIGNING_STORE_PASS: $(AndroidSigningStorePass)
      ANDROID_SIGNING_KEY_PASS: $(AndroidSigningKeyPass)

  - pwsh: |
      dotnetdeployer
    displayName: Create GitHub release packages
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/main')))
    env:
      GITHUB_TOKEN: $(GitHubApiKey)
      ANDROID_KEYSTORE_BASE64: $(AndroidBase64Keystore)
      ANDROID_SIGNING_STORE_PASS: $(AndroidSigningStorePass)
      ANDROID_SIGNING_KEY_PASS: $(AndroidSigningKeyPass)
